filegroup(
    name = "sources",
    srcs = glob(include = ["**"], exclude_dirs = 0, exclude = ["Cargo.toml", "Cargo.lock"]),
)

filegroup(
    name = "cargo_lock",
    srcs = ["Cargo.lock"],
)

filegroup(
    name = "cargo_toml",
    srcs = ["Cargo.toml"],
)
